# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8766fbaea20c9388ab1ed8c4ac4cbc1e6cc28e5cc76ae9a22f75c084ee31f59cab3b9d8373df82f3dfae58a564022ff5c68590e0891312edf71cd3afceed58

test:
  secret_key_base: d7e431986042f498a612f126371630586c18771b52e0ca8437963e75d0182cef6fa4aab2f691c5149106c4c788de1f7530f8a0a8497ce471afe1ae579f395ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
